# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.4
_src_path: https://github.com/delorenj/CommonProject
project_description: Workflow tools to help DigiPop create editable assets
project_name: DigiPop
